name: buildfork

permissions:
  actions: write

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://spiteful-snow.surge.sh
    steps:
      - name: download build artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: build
      - name: deploy to surge
        run: npx surge --project '.' --domain spiteful-snow.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage # artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: build

          
