name: buildfork

on:
  workflow_dispatch: # let it work manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage # artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: build

          
